# Generated by Django 3.1.7 on 2022-01-06 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Travels_place_table', '0026_auto_20220106_1038'),
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checkout_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_per_night',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_size',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_slug',
        ),
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
        migrations.AddField(
            model_name='booking',
            name='No_of_people',
            field=models.IntegerField(default='3', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='User',
            field=models.ForeignKey(default='41', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(blank=True, default='2021-12-27'),
        ),
        migrations.AddField(
            model_name='room',
            name='From',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='TO',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='travels_place_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Travels_place_table.travelsplacesinformation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checking_date',
            field=models.DateField(blank=True, default='2021-12-23'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_booked',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='Departure_Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=50)),
                ('travels_place_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Travels_place_table.travelsplacesinformation')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='Month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.departure_month'),
        ),
    ]
