# Generated by Django 3.1.7 on 2022-01-19 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Travels_Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Title', models.CharField(default='pokhara', max_length=36)),
                ('Blog_Description', models.TextField(null=True)),
                ('Image', models.ImageField(blank=True, default='/profile_icon/1.jpg', upload_to='Travels_Blogs/pictures')),
                ('slug', models.SlugField(default='pkr')),
                ('comments', models.TextField(default='your own content')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
