# Generated by Django 3.1.7 on 2022-01-19 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Travels_Blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travels_blogs',
            name='author',
        ),
        migrations.RemoveField(
            model_name='travels_blogs',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='travels_blogs',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='travels_blogs',
            name='updated_on',
        ),
        migrations.CreateModel(
            name='Travels_Blogs_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(default='your own content')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('Travels_Blogs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Travels_Blogs.travels_blogs')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
