# Generated by Django 3.1.7 on 2022-01-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_Blogs', '0002_auto_20220119_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travels_blogs_comment',
            old_name='author',
            new_name='user',
        ),
    ]
