# Generated by Django 3.1.7 on 2022-01-20 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Travels_Blogs', '0003_auto_20220119_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travels_Blogs_Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Our own title', max_length=35)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
