# Generated by Django 3.1.7 on 2022-01-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_Blogs', '0004_travels_blogs_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels_blogs_gallery',
            name='Image',
            field=models.ImageField(blank=True, default='/profile_icon/1.jpg', upload_to='Travels_Blogs/pictures'),
        ),
    ]
