# Generated by Django 3.1.7 on 2022-01-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_Blogs', '0005_travels_blogs_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels_blogs',
            name='summary',
            field=models.CharField(default='your own word', max_length=2000),
        ),
    ]
