# Generated by Django 3.1.7 on 2022-01-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_Blogs', '0008_travels_blogs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels_blogs',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='travels_blogs',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
