# Generated by Django 3.1.7 on 2022-01-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_Blogs', '0012_auto_20220125_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels_blogs',
            name='Blog_Title',
            field=models.CharField(default='pokhara', max_length=1000),
        ),
    ]
