# Generated by Django 3.1.7 on 2022-01-28 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Travels_Blogs', '0013_auto_20220126_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='Blogs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Travels_Blogs.travels_blogs'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(default='Our own word', max_length=7500),
        ),
    ]
