# Generated by Django 3.1.7 on 2022-01-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_Blogs', '0014_auto_20220128_1626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
