# Generated by Django 3.1.7 on 2022-02-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_Blogs', '0015_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels_blogs',
            name='clicks',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='travels_blogs',
            name='slug',
            field=models.SlugField(default='pkr', max_length=250),
        ),
    ]
