# Generated by Django 3.1.7 on 2022-02-26 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0043_suitable_date_discount'),
        ('Travels_Blogs', '0016_auto_20220225_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='Travels_place_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Travels_place_table.travelsplacesinformation'),
        ),
    ]
