# Generated by Django 3.1.7 on 2022-02-27 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_Blogs', '0017_wishlist_travels_place_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='Activity_Level',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='Blogs',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='Duration',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='category',
        ),
    ]
