# Generated by Django 3.1.7 on 2021-12-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_api', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Profile_Image',
            field=models.ImageField(null=True, upload_to='user/%Y/'),
        ),
    ]
