# Generated by Django 3.1.7 on 2022-01-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_api', '0003_auto_20211221_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Profile_Image',
            field=models.ImageField(default='static/images/1.jpg', upload_to='user/%Y/'),
        ),
    ]
