# Generated by Django 3.1.7 on 2022-01-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_api', '0006_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Address_line1',
            field=models.CharField(default='Locality/Houses/Street No', max_length=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Address_line2',
            field=models.CharField(default='Village/City Name', max_length=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Country',
            field=models.CharField(default='Nepal', max_length=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Country_code',
            field=models.ImageField(default='2500', upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Date_of_Birth',
            field=models.DateField(default='2021-12-27'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], default='Enter your Gender', max_length=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Postal_Code',
            field=models.IntegerField(default='356'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='State',
            field=models.CharField(default='Enter your State name', max_length=1200),
        ),
    ]
