# Generated by Django 3.1.7 on 2022-01-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_api', '0007_auto_20220125_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Country_code',
            field=models.IntegerField(default='2500'),
        ),
    ]
