# Generated by Django 3.1.7 on 2021-12-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0002_auto_20211226_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelsplacesinformation',
            name='travels_place_image',
            field=models.ImageField(null=True, upload_to='places/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='travelsplacesinformation',
            name='travels_place_image1',
            field=models.ImageField(null=True, upload_to='places/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='travelsplacesinformation',
            name='travels_place_image2',
            field=models.ImageField(null=True, upload_to='places/%Y/%m/'),
        ),
    ]
