# Generated by Django 3.1.7 on 2021-12-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0003_auto_20211226_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departure_Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=50)),
                ('travels_place_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_Date', to='Travels_place_table.travelsplacesinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Suitable_Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.DateField(null=True)),
                ('TO', models.DateField(null=True)),
                ('day_name', models.CharField(max_length=100)),
                ('Month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suitable_days', to='Travels_place_table.departure_month')),
            ],
        ),
        migrations.RemoveField(
            model_name='month',
            name='travels_place_information',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
