# Generated by Django 3.1.7 on 2021-12-27 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0004_auto_20211226_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelsplacesinformation',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='departure_month',
            name='travels_place_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_Month', to='Travels_place_table.travelsplacesinformation'),
        ),
        migrations.AlterField(
            model_name='suitable_date',
            name='Month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suitable_date', to='Travels_place_table.departure_month'),
        ),
    ]
