# Generated by Django 3.1.7 on 2021-12-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0005_auto_20211227_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelsplacesinformation',
            name='Max_range',
        ),
        migrations.RemoveField(
            model_name='travelsplacesinformation',
            name='Min_range',
        ),
        migrations.RemoveField(
            model_name='travelsplacesinformation',
            name='Travels_place_Description',
        ),
        migrations.AddField(
            model_name='travelsplacesinformation',
            name='Age_range',
            field=models.IntegerField(default='12'),
        ),
    ]
