# Generated by Django 3.1.7 on 2021-12-27 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0006_auto_20211227_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_and_end_Path', models.CharField(db_index=True, default='pokhara', max_length=400)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travels_place_table.travelsplacepath')),
            ],
        ),
    ]
