# Generated by Django 3.1.7 on 2021-12-27 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0007_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.AlterField(
            model_name='tag',
            name='Start_and_end_Path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travels_place_table.travelsplacepath'),
        ),
    ]
