# Generated by Django 3.1.7 on 2021-12-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0010_remove_travelsplacesinformation_travels_package_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tag',
        ),
    ]
