# Generated by Django 3.1.7 on 2021-12-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0011_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travels_package',
            name='Travels_package_name',
        ),
        migrations.AddField(
            model_name='travelsplacepath',
            name='Tour_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
