# Generated by Django 3.1.7 on 2021-12-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0012_auto_20211228_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_rating',
            name='Rating_Description',
            field=models.TextField(null=True),
        ),
    ]
