# Generated by Django 3.1.7 on 2022-01-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0013_user_rating_rating_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelsplacesinformation',
            name='map',
            field=models.TextField(null=True),
        ),
    ]
