# Generated by Django 3.1.7 on 2022-01-04 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0015_auto_20220104_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitable_date',
            name='travels_place_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_Date', to='Travels_place_table.travelsplacesinformation'),
        ),
    ]
