# Generated by Django 3.1.7 on 2022-01-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0017_cost_details_highlights_suitable_places'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suitable_Places',
        ),
    ]
