# Generated by Django 3.1.7 on 2022-01-04 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0018_delete_suitable_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suitable_Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='places/Suitable_places')),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='places/Suitable_places')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='places/Suitable_places')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='places/Suitable_places')),
                ('Image4', models.ImageField(blank=True, null=True, upload_to='places/Suitable_places')),
                ('travels_place_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travels_place_table.travelsplacesinformation')),
            ],
        ),
    ]
