# Generated by Django 3.1.7 on 2022-01-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0019_suitable_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure_month',
            name='month_name',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=50),
        ),
    ]
