# Generated by Django 3.1.7 on 2022-01-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0020_auto_20220105_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure_month',
            name='month_name',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August')], max_length=50),
        ),
    ]
