# Generated by Django 3.1.7 on 2022-01-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0021_auto_20220105_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure_month',
            name='month_name',
            field=models.CharField(max_length=50),
        ),
    ]
