# Generated by Django 3.1.7 on 2022-01-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0022_auto_20220105_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelsplacesinformation',
            name='Travels_category',
        ),
    ]
