# Generated by Django 3.1.7 on 2022-01-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0023_remove_travelsplacesinformation_travels_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelsplacesinformation',
            old_name='Age_range',
            new_name='Max_Age_range',
        ),
        migrations.AddField(
            model_name='travelsplacesinformation',
            name='Min_Age_range',
            field=models.IntegerField(default='12'),
        ),
    ]
