# Generated by Django 3.1.7 on 2022-01-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0024_auto_20220105_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelsplacesinformation',
            name='Description',
            field=models.TextField(null='true'),
            preserve_default='true',
        ),
    ]
