# Generated by Django 3.1.7 on 2022-01-06 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0025_travelsplacesinformation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_rating',
            name='Rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
