# Generated by Django 3.1.7 on 2022-01-12 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0027_remove_suitable_date_day_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelsplacesinformation',
            name='Travels_Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Travels_place_table.travels_category'),
        ),
    ]
