# Generated by Django 3.1.7 on 2022-01-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0028_travelsplacesinformation_travels_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travels_Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Title', models.CharField(max_length=36, null=True)),
                ('Blog_Description', models.TextField(null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
    ]
