# Generated by Django 3.1.7 on 2022-01-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0029_travels_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels_blogs',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Travels_Blogs/pictures'),
        ),
    ]
