# Generated by Django 3.1.7 on 2022-01-19 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Travels_place_table', '0030_travels_blogs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels_blogs',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travels_blogs',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
