# Generated by Django 3.1.7 on 2022-01-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0031_auto_20220119_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels_blogs',
            name='Blog_Title',
            field=models.CharField(default='pokhara', max_length=36),
        ),
        migrations.AlterField(
            model_name='travels_blogs',
            name='Image',
            field=models.ImageField(blank=True, default='/profile_icon/1.jpg', upload_to='Travels_Blogs/pictures'),
        ),
    ]
