# Generated by Django 3.1.7 on 2022-01-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0032_auto_20220119_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels_blogs',
            name='comments',
            field=models.TextField(default='your own content'),
        ),
    ]
