# Generated by Django 3.1.7 on 2022-01-19 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Travels_place_table', '0033_auto_20220119_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels_blogs',
            name='author',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='travels_blogs',
            name='slug',
            field=models.SlugField(default='pkr', null=True),
        ),
    ]
