# Generated by Django 3.1.7 on 2022-01-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0035_auto_20220119_1011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Travels_Blogs',
        ),
    ]
