# Generated by Django 3.1.7 on 2022-01-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0036_delete_travels_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_details',
            name='travels_place_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_details', to='Travels_place_table.travelsplacesinformation'),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='travels_place_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='Travels_place_table.travelsplacesinformation'),
        ),
        migrations.AlterField(
            model_name='suitable_places',
            name='travels_place_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suitable_places', to='Travels_place_table.travelsplacesinformation'),
        ),
    ]
