# Generated by Django 3.1.7 on 2022-01-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0037_auto_20220119_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelsplacesinformation',
            name='Total_cost',
            field=models.IntegerField(default='1000'),
        ),
    ]
