# Generated by Django 3.1.7 on 2022-01-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0038_auto_20220119_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelsplacesinformation',
            old_name='Description',
            new_name='Overview',
        ),
        migrations.RemoveField(
            model_name='travelsplacepath',
            name='Tour_id',
        ),
        migrations.AddField(
            model_name='travelsplacesinformation',
            name='summary',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='travelsplacesinformation',
            name='map',
            field=models.CharField(default='Paste the link here', max_length=2000),
        ),
    ]
