# Generated by Django 3.1.7 on 2022-01-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0040_auto_20220122_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='departure_month',
            name='year_name',
            field=models.CharField(default='Jun', max_length=500),
        ),
        migrations.AlterField(
            model_name='departure_month',
            name='month_name',
            field=models.CharField(max_length=509),
        ),
    ]
