# Generated by Django 3.1.7 on 2022-01-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0041_auto_20220122_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure_month',
            name='year_name',
            field=models.CharField(default='2022', max_length=500),
        ),
    ]
