# Generated by Django 3.1.7 on 2022-02-26 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels_place_table', '0042_auto_20220122_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitable_date',
            name='Discount',
            field=models.ImageField(default='12%', upload_to='', verbose_name=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
